USE sakila;

-- CHALLENGE

-- Write SQL queries to perform the following tasks using the Sakila database:
	-- List the number of films per category.
    -- Retrieve the store ID, city, and country for each store.
    -- Calculate the total revenue generated by each store in dollars.
    -- Determine the average running time of films for each category.
    -- Identify the film categories with the longest average running time.
    -- Display the top 10 most frequently rented movies in descending order.
    -- Determine if "Academy Dinosaur" can be rented from Store 1.
    -- Provide a list of all distinct film titles, along with their availability status in the inventory. 
    -- Include a column indicating whether each title is 'Available' or 'NOT available.' 
    -- Note that there are 42 titles that are not in the inventory, and this information can be obtained using a CASE statement combined with IFNULL."


SELECT category.name, COUNT(film.film_id) AS total_films
FROM film
INNER JOIN film_category
ON film.film_id = film_category.film_id
INNER JOIN category
ON film_category.category_id = category.category_id
GROUP BY category.name;

SELECT store.store_id, city.city, country.country
FROM store
INNER JOIN address
ON store.address_id = address.address_id
INNER JOIN city
ON address.city_id = city.city_id
INNER JOIN country
ON city.country_id = country.country_id;

SELECT store.store_id, SUM(payment.amount) AS total_revenue
FROM store
INNER JOIN staff
ON store.store_id = staff.store_id
INNER JOIN payment
ON staff.staff_id = payment.staff_id
GROUP BY store.store_id;

SELECT category.name, AVG(film.length) AS average_length
FROM film
INNER JOIN film_category
ON film.film_id = film_category.film_id
INNER JOIN category
ON film_category.category_id = category.category_id
GROUP BY category.name;

SELECT category.name, AVG(film.length) AS average_length
FROM film
INNER JOIN film_category
ON film.film_id = film_category.film_id
INNER JOIN category
ON film_category.category_id = category.category_id
GROUP BY category.name
ORDER BY average_length DESC;

SELECT film.title, COUNT(rental.rental_id) AS frequency
FROM film
INNER JOIN inventory
ON film.film_id = inventory.film_id
INNER JOIN rental
ON inventory.inventory_id = rental.inventory_id
GROUP BY film.title
ORDER BY frequency DESC
LIMIT 10;

SELECT film.title, store.store_id
FROM film
INNER JOIN inventory
ON film.film_id = inventory.film_id
INNER JOIN store
ON inventory.store_id = store.store_id
WHERE film.title = "Academy Dinosaur" AND store.store_id = 1;

SELECT
	film.title,
	CASE 
		WHEN IFNULL(inventory.inventory_id, 0) = 0 THEN 'NOT available'
		ELSE 'Available'
    END AS availability
FROM film
LEFT JOIN inventory
ON film.film_id = inventory.film_id
GROUP BY film.title, availability;





















